### ISSUE TITLE
TikaException: TIKA-198

### ISSUE THREAD

**Issue by aleha84** [Norconex/importer#41] opened 2017-04-04 05:31 UTC
There are a lot of this kind exceptions in log file. 

```
com.norconex.importer.parser.DocumentParserException: org.apache.tika.exception.TikaException: 
TIKA-198: Illegal IOException from org.apache.tika.parser.microsoft.OfficeParser@6f8fdac3

...

Caused by: org.apache.poi.poifs.filesystem.NotOLE2FileException: Invalid header signature; 
read 0x615C316674725C7B, expected 0xE11AB1A1E011CFD0 - Your file appears not to be a valid OLE2 document
```

Is it right to ask here? Or i should write open issue somewhere more?

**Comment by essiembre** [comment] 2017-04-04 06:11
It could be an unsupported file format, a corrupted file, or else.  Can you attach a file causing this exception?

**Comment by aleha84** [comment] 2017-04-05 05:56
Sent you an email. All listed there files opens normally, without errors.

**Comment by essiembre** [comment] 2017-04-05 21:01
Which version are you using to test?  I just tried with the latest Importer snapshot and I was able to parse the first 3 of the 5 files you sent me.  I sent you an email with the parsed output.  

I will investigate the other two further (eq-all-en.xls and metod-2013.doc).

**Comment by essiembre** [comment] 2017-04-05 21:20
I found out why some are failing.    You are using HTTP Collector and the content type from the HTTP response does not match the real content type of the file.  For instance, your ``...agreement.rtf`` file is identified as ``application/msword`` when returned by your web server.  In reality the document is ``application/rtf``.   

The Importer module will try to guess the content type when it is not provided.  It otherwise uses the provided one (from the HTTP response in your case).   So you should really be looking at why your web server does not return the proper content type for some documents.  Fixing this will fix many of your errors.

If you do not control the site or it is otherwise impossible for you to do, we can make a feature request to always "guess" the content type instead of trusting the web server.  I am not sure whether this could cause additional issues though (when guessing is wrong).

**Comment by essiembre** [comment] 2017-04-05 22:37
Your ``metod-2013.doc`` file fails due to a bug that will be fixed in next Tika release: https://issues.apache.org/jira/browse/TIKA-2198
Until it is released, I have integrated the single fix myself, found in latest [snapshot](https://www.norconex.com/collectors/importer/download) version of the Importer.

Your ``eq-all-en.xls`` file is more tricky.  I researched this specific exception and it seems to point to an issue with how the file was written, even if it can be opened properly by Excel.   A known workaround is to save the file in the newer Microsoft format (.xlsx).  I tested this and that works.

**Comment by aleha84** [comment] 2017-04-06 06:26
most interested in fixing org.apache.poi.poifs.filesystem.NotOLE2FileException. The rest are a single cases. 

> feature request to always "guess" the content type instead of trusting the web server

It will be great. But could it be more flexible to compare content type sended by server and real content type? And if it differs use real insted of provided by server.

**Comment by essiembre** [comment] 2017-04-06 17:20
What your suggesting is equivalent to always using/guessing the real one.  I will mark this as a feature request.  I plan to add a flag to that effect.

**Comment by essiembre** [comment] 2017-04-12 03:06
A new [snapshot release of the HTTP Collector](https://www.norconex.com/collectors/collector-http/download) was made which now offers to detect the content type and character encoding instead of relying on the HTTP header response.  It can be enabled like this (in your crawler section):

```xml
<documentFetcher detectContentType="true" detectCharset="true"/>
```

FYI, when used standalone, the Importer will always try to detect the content type and character encoding when not specified.

**Comment by essiembre** [comment] 2017-04-26 05:09
Stable 2.7.0 was just released with this fix.

**Closed by essiembre** 2017-04-26 05:09 UTC
Labels: feature-request, fixed/done

**Comment by aleha84** [comment] 2017-04-26 15:52
great, thx

**Comment by ciroppina** [comment] 2019-01-29 13:16
for all interted people: Same exceptionappears with Norconex Collector 2.8.1, while trying to extract RTF and DOCX documents from imported/fetched .zip archives

**Comment by SaschaHeyer** [comment] 2019-04-16 08:04
I can confirm the same behavior (org.apache.tika.exception.TikaException: TIKA-198) also for .jpg in .zip archives. 

Norconex Collector 2.8.1

**Comment by essiembre** [comment] 2019-04-20 03:21
You tried ``<documentFetcher detectContentType="true" detectCharset="true"/>``?  If so, can you confirm whether you are using pre-parse handlers?  If so, do you make sure you are not performing text operations on binary files (using ``restrictTo``)?   If that is not your issue, please open a new ticket (since this one is closed) with details to reproduce.
